name: Update F-Droid Repo
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (Критически важно для подписи индекса)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install F-Droid Server
        run: |
          sudo apt-get update
          sudo apt-get install -y fdroidserver

      - name: Initialize and Update Repo
        run: |
          # Создаем пустую папку метаданных, чтобы fdroid не падал
          mkdir -p metadata
          # Инициализируем конфиг (ключи подписи создадутся автоматически)
          fdroid init --dist
          # Генерируем индекс магазина. 
          # Флаг --pretty делает файл читаемым, --create-metadata собирает инфо из APK.
          fdroid update --create-metadata --pretty

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'repo/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
